packages:
  - "packages/**"

catalog:
  "@restatedev/restate-sdk": ^1.8.1
  "@restatedev/restate-sdk-clients": ^1.8.1
  "@restatedev/restate-sdk-testcontainers": ^1.8.1
  "@restatedev/restate-sdk-zod": ^1.8.1
  zod: ^3.25.76
  testcontainers: ^10.24.1

onlyBuiltDependencies:
  - cpu-features
  - esbuild
