packages:
  - "packages/**"

catalog:
  "@restatedev/restate-sdk": ^1.9.1
  "@restatedev/restate-sdk-clients": ^1.9.1
  "@restatedev/restate-sdk-testcontainers": ^1.9.1
  "@restatedev/restate-sdk-zod": ^1.9.1
  zod: ^4.0.0
  testcontainers: ^10.24.1

onlyBuiltDependencies:
  - cpu-features
  - esbuild
